# Generated by Django 4.0.4 on 2022-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('is_enable', models.BooleanField(default=False)),
                ('publish_date', models.DateField()),
                ('created_date', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
    ]
