# Generated by Django 4.0.4 on 2022-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_auth_alter_user_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
