# Generated by Django 4.0.4 on 2022-07-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_tokenlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokenlist',
        ),
    ]
