# Generated by Django 4.0.4 on 2022-07-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(default='#', max_length=12, unique=True),
        ),
    ]
