# Generated by Django 4.0.4 on 2022-07-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='name',
        ),
    ]
