# Generated by Django 4.0.4 on 2022-07-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_phone_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Phone',
        ),
    ]
