# Generated by Django 4.0.4 on 2022-07-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
