# Generated by Django 4.0.4 on 2022-07-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Phone',
        ),
    ]
