# Generated by Django 4.0.4 on 2022-07-05 08:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
