# Generated by Django 4.0.4 on 2022-07-05 09:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
