# Generated by Django 4.0.4 on 2022-07-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
