# Generated by Django 4.0.4 on 2022-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
