# Generated by Django 4.0.4 on 2022-07-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OTP',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
