# Generated by Django 4.0.4 on 2022-07-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
