# Generated by Django 4.0.4 on 2022-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
