# Generated by Django 4.0.4 on 2022-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_time',
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
