# Generated by Django 4.0.4 on 2022-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_user_otp_remove_user_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
