# Generated by Django 4.0.4 on 2022-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
